apiVersion : apps/v1
kind: Deployment
metadata:
  name: webcrawlerimage 
spec:
  replicas: 10
  selector:
    matchLabels:
      app: webcrawlerimage
  template:
    metadata:
      labels:
        app: webcrawlerimage 
    spec:
      containers:
        - name: webcrawlerimage 
          image: webcrawlercontainerregistry.azurecr.io/webcrawlerimage
          ports:
          - containerPort: 80